module.exports = [
  {
    component: 'Accordion',
    componentType: 'accordion',
    lowercase: 'accordion',
    uppercamelcase: 'Accordion',
    lowercamelcase: 'accordion',
    snakecase: 'ACCORDION',
    kebabcase: 'accordion',
    disabled: false,
    category: 'navigations',
    capitalizedcategory: 'Navigations',
  },
  {
    component: 'Alert',
    componentType: 'alert',
    lowercase: 'alert',
    uppercamelcase: 'Alert',
    lowercamelcase: 'alert',
    snakecase: 'ALERT',
    kebabcase: 'alert',
    disabled: false,
    category: 'texts',
    capitalizedcategory: 'Texts',
  },
  {
    component: 'AppBar',
    componentType: 'appbar',
    lowercase: 'appbar',
    uppercamelcase: 'AppBar',
    lowercamelcase: 'appBar',
    snakecase: 'APP_BAR',
    kebabcase: 'app-bar',
    disabled: false,
    category: 'navigations',
    capitalizedcategory: 'Navigations',
  },
  {
    component: 'Autocomplete',
    componentType: 'autocomplete',
    lowercase: 'autocomplete',
    uppercamelcase: 'Autocomplete',
    lowercamelcase: 'autocomplete',
    snakecase: 'AUTOCOMPLETE',
    kebabcase: 'autocomplete',
    disabled: false,
    category: 'inputs',
    capitalizedcategory: 'Inputs',
  },
  {
    component: 'Avatar',
    componentType: 'avatar',
    lowercase: 'avatar',
    uppercamelcase: 'Avatar',
    lowercamelcase: 'avatar',
    snakecase: 'AVATAR',
    kebabcase: 'avatar',
    disabled: false,
    category: 'displays',
    capitalizedcategory: 'Displays',
  },
  {
    component: 'AvatarGroup',
    componentType: 'avatargroup',
    lowercase: 'avatargroup',
    uppercamelcase: 'AvatarGroup',
    lowercamelcase: 'avatarGroup',
    snakecase: 'AVATAR_GROUP',
    kebabcase: 'avatar-group',
    disabled: false,
    category: 'displays',
    capitalizedcategory: 'Displays',
  },
  {
    component: 'Backdrop',
    componentType: 'backdrop',
    lowercase: 'backdrop',
    uppercamelcase: 'Backdrop',
    lowercamelcase: 'backdrop',
    snakecase: 'BACKDROP',
    kebabcase: 'backdrop',
    disabled: false,
    category: 'popups',
    capitalizedcategory: 'Popups',
  },
  {
    component: 'Badge',
    componentType: 'badge',
    lowercase: 'badge',
    uppercamelcase: 'Badge',
    lowercamelcase: 'badge',
    snakecase: 'BADGE',
    kebabcase: 'badge',
    disabled: false,
    category: 'displays',
    capitalizedcategory: 'Displays',
  },
  {
    component: 'BottomNavigation',
    componentType: 'bottomnavigation',
    lowercase: 'bottomnavigation',
    uppercamelcase: 'BottomNavigation',
    lowercamelcase: 'bottomNavigation',
    snakecase: 'BOTTOM_NAVIGATION',
    kebabcase: 'bottom-navigation',
    disabled: false,
    category: 'navigations',
    capitalizedcategory: 'Navigations',
  },
  {
    component: 'Box',
    componentType: 'box',
    lowercase: 'box',
    uppercamelcase: 'Box',
    lowercamelcase: 'box',
    snakecase: 'BOX',
    kebabcase: 'box',
    disabled: false,
    category: 'layouts',
    capitalizedcategory: 'Layouts',
  },
  {
    component: 'Breadcrumbs',
    componentType: 'breadcrumbs',
    lowercase: 'breadcrumbs',
    uppercamelcase: 'Breadcrumbs',
    lowercamelcase: 'breadcrumbs',
    snakecase: 'BREADCRUMBS',
    kebabcase: 'breadcrumbs',
    disabled: false,
    category: 'navigations',
    capitalizedcategory: 'Navigations',
  },
  {
    component: 'Button',
    componentType: 'button',
    lowercase: 'button',
    uppercamelcase: 'Button',
    lowercamelcase: 'button',
    snakecase: 'BUTTON',
    kebabcase: 'button',
    disabled: false,
    category: 'buttons',
    capitalizedcategory: 'Buttons',
  },
  {
    component: 'ButtonGroup',
    componentType: 'buttongroup',
    lowercase: 'buttongroup',
    uppercamelcase: 'ButtonGroup',
    lowercamelcase: 'buttonGroup',
    snakecase: 'BUTTON_GROUP',
    kebabcase: 'button-group',
    disabled: false,
    category: 'buttons',
    capitalizedcategory: 'Buttons',
  },
  {
    component: 'Card',
    componentType: 'card',
    lowercase: 'card',
    uppercamelcase: 'Card',
    lowercamelcase: 'card',
    snakecase: 'CARD',
    kebabcase: 'card',
    disabled: true,
    category: 'containers',
    capitalizedcategory: 'Containers',
  },
  {
    component: 'Checkbox',
    componentType: 'checkbox',
    lowercase: 'checkbox',
    uppercamelcase: 'Checkbox',
    lowercamelcase: 'checkbox',
    snakecase: 'CHECKBOX',
    kebabcase: 'checkbox',
    disabled: true,
    category: 'inputs',
    capitalizedcategory: 'Inputs',
  },
  {
    component: 'Chip',
    componentType: 'chip',
    lowercase: 'chip',
    uppercamelcase: 'Chip',
    lowercamelcase: 'chip',
    snakecase: 'CHIP',
    kebabcase: 'chip',
    disabled: false,
    category: 'displays',
    capitalizedcategory: 'Displays',
  },
  {
    component: 'CircularProgress',
    componentType: 'circularprogress',
    lowercase: 'circularprogress',
    uppercamelcase: 'CircularProgress',
    lowercamelcase: 'circularProgress',
    snakecase: 'CIRCULAR_PROGRESS',
    kebabcase: 'circular-progress',
    disabled: false,
    category: 'popups',
    capitalizedcategory: 'Popups',
  },
  {
    component: 'Collapse',
    componentType: 'collapse',
    lowercase: 'collapse',
    uppercamelcase: 'Collapse',
    lowercamelcase: 'collapse',
    snakecase: 'COLLAPSE',
    kebabcase: 'collapse',
    disabled: false,
    category: 'animations',
    capitalizedcategory: 'Animations',
  },
  {
    component: 'Container',
    componentType: 'container',
    lowercase: 'container',
    uppercamelcase: 'Container',
    lowercamelcase: 'container',
    snakecase: 'CONTAINER',
    kebabcase: 'container',
    disabled: true,
    category: 'containers',
    capitalizedcategory: 'Containers',
  },
  {
    component: 'Dialog',
    componentType: 'dialog',
    lowercase: 'dialog',
    uppercamelcase: 'Dialog',
    lowercamelcase: 'dialog',
    snakecase: 'DIALOG',
    kebabcase: 'dialog',
    disabled: true,
    category: 'popups',
    capitalizedcategory: 'Popups',
  },
  {
    component: 'Divider',
    componentType: 'divider',
    lowercase: 'divider',
    uppercamelcase: 'Divider',
    lowercamelcase: 'divider',
    snakecase: 'DIVIDER',
    kebabcase: 'divider',
    disabled: false,
    category: 'layouts',
    capitalizedcategory: 'Layouts',
  },
  {
    component: 'Drawer',
    componentType: 'drawer',
    lowercase: 'drawer',
    uppercamelcase: 'Drawer',
    lowercamelcase: 'drawer',
    snakecase: 'DRAWER',
    kebabcase: 'drawer',
    disabled: false,
    category: 'navigations',
    capitalizedcategory: 'Navigations',
  },
  {
    component: 'Fab',
    componentType: 'fab',
    lowercase: 'fab',
    uppercamelcase: 'Fab',
    lowercamelcase: 'fab',
    snakecase: 'FAB',
    kebabcase: 'fab',
    disabled: false,
    category: 'buttons',
    capitalizedcategory: 'Buttons',
  },
  {
    component: 'Fade',
    componentType: 'fade',
    lowercase: 'fade',
    uppercamelcase: 'Fade',
    lowercamelcase: 'fade',
    snakecase: 'FADE',
    kebabcase: 'fade',
    disabled: false,
    category: 'animations',
    capitalizedcategory: 'Animations',
  },
  {
    component: 'FormControl',
    componentType: 'formcontrol',
    lowercase: 'formcontrol',
    uppercamelcase: 'FormControl',
    lowercamelcase: 'formControl',
    snakecase: 'FORM_CONTROL',
    kebabcase: 'form-control',
    disabled: false,
    category: 'forms',
    capitalizedcategory: 'Forms',
  },
  {
    component: 'FormControlLabel',
    componentType: 'formcontrollabel',
    lowercase: 'formcontrollabel',
    uppercamelcase: 'FormControlLabel',
    lowercamelcase: 'formControlLabel',
    snakecase: 'FORM_CONTROL_LABEL',
    kebabcase: 'form-control-label',
    disabled: true,
    category: 'forms',
    capitalizedcategory: 'Forms',
  },
  {
    component: 'FormGroup',
    componentType: 'formgroup',
    lowercase: 'formgroup',
    uppercamelcase: 'FormGroup',
    lowercamelcase: 'formGroup',
    snakecase: 'FORM_GROUP',
    kebabcase: 'form-group',
    disabled: false,
    category: 'forms',
    capitalizedcategory: 'Forms',
  },
  {
    component: 'FormHelperText',
    componentType: 'formhelpertext',
    lowercase: 'formhelpertext',
    uppercamelcase: 'FormHelperText',
    lowercamelcase: 'formHelperText',
    snakecase: 'FORM_HELPER_TEXT',
    kebabcase: 'form-helper-text',
    disabled: false,
    category: 'forms',
    capitalizedcategory: 'Forms',
  },
  {
    component: 'FormLabel',
    componentType: 'formlabel',
    lowercase: 'formlabel',
    uppercamelcase: 'FormLabel',
    lowercamelcase: 'formLabel',
    snakecase: 'FORM_LABEL',
    kebabcase: 'form-label',
    disabled: false,
    category: 'forms',
    capitalizedcategory: 'Forms',
  },
  {
    component: 'Grid',
    componentType: 'grid',
    lowercase: 'grid',
    uppercamelcase: 'Grid',
    lowercamelcase: 'grid',
    snakecase: 'GRID',
    kebabcase: 'grid',
    disabled: false,
    category: 'layouts',
    capitalizedcategory: 'Layouts',
  },
  {
    component: 'Grow',
    componentType: 'grow',
    lowercase: 'grow',
    uppercamelcase: 'Grow',
    lowercamelcase: 'grow',
    snakecase: 'GROW',
    kebabcase: 'grow',
    disabled: false,
    category: 'animations',
    capitalizedcategory: 'Animations',
  },
  {
    component: 'Hidden',
    componentType: 'hidden',
    lowercase: 'hidden',
    uppercamelcase: 'Hidden',
    lowercamelcase: 'hidden',
    snakecase: 'HIDDEN',
    kebabcase: 'hidden',
    disabled: false,
    category: 'animations',
    capitalizedcategory: 'Animations',
  },
  {
    component: 'Icon',
    componentType: 'icon',
    lowercase: 'icon',
    uppercamelcase: 'Icon',
    lowercamelcase: 'icon',
    snakecase: 'ICON',
    kebabcase: 'icon',
    disabled: false,
    category: 'displays',
    capitalizedcategory: 'Displays',
  },
  {
    component: 'IconButton',
    componentType: 'iconbutton',
    lowercase: 'iconbutton',
    uppercamelcase: 'IconButton',
    lowercamelcase: 'iconButton',
    snakecase: 'ICON_BUTTON',
    kebabcase: 'icon-button',
    disabled: false,
    category: 'buttons',
    capitalizedcategory: 'Buttons',
  },
  {
    component: 'ImageList',
    componentType: 'imagelist',
    lowercase: 'imagelist',
    uppercamelcase: 'ImageList',
    lowercamelcase: 'imageList',
    snakecase: 'IMAGE_LIST',
    kebabcase: 'image-list',
    disabled: false,
    category: 'lists',
    capitalizedcategory: 'Lists',
  },
  {
    component: 'LinearProgress',
    componentType: 'linearprogress',
    lowercase: 'linearprogress',
    uppercamelcase: 'LinearProgress',
    lowercamelcase: 'linearProgress',
    snakecase: 'LINEAR_PROGRESS',
    kebabcase: 'linear-progress',
    disabled: false,
    category: 'popups',
    capitalizedcategory: 'Popups',
  },
  {
    component: 'Link',
    componentType: 'link',
    lowercase: 'link',
    uppercamelcase: 'Link',
    lowercamelcase: 'link',
    snakecase: 'LINK',
    kebabcase: 'link',
    disabled: false,
    category: 'buttons',
    capitalizedcategory: 'Buttons',
  },
  {
    component: 'List',
    componentType: 'list',
    lowercase: 'list',
    uppercamelcase: 'List',
    lowercamelcase: 'list',
    snakecase: 'LIST',
    kebabcase: 'list',
    disabled: true,
    category: 'lists',
    capitalizedcategory: 'Lists',
  },
  {
    component: 'LoadingButton',
    componentType: 'loadingbutton',
    lowercase: 'loadingbutton',
    uppercamelcase: 'LoadingButton',
    lowercamelcase: 'loadingButton',
    snakecase: 'LOADING_BUTTON',
    kebabcase: 'loading-button',
    disabled: true,
    category: 'buttons',
    capitalizedcategory: 'Buttons',
  },
  {
    component: 'Masonry',
    componentType: 'masonry',
    lowercase: 'masonry',
    uppercamelcase: 'Masonry',
    lowercamelcase: 'masonry',
    snakecase: 'MASONRY',
    kebabcase: 'masonry',
    disabled: true,
    category: 'layouts',
    capitalizedcategory: 'Layouts',
  },
  {
    component: 'Menu',
    componentType: 'menu',
    lowercase: 'menu',
    uppercamelcase: 'Menu',
    lowercamelcase: 'menu',
    snakecase: 'MENU',
    kebabcase: 'menu',
    disabled: false,
    category: 'menus',
    capitalizedcategory: 'Menus',
  },
  {
    component: 'MobileStepper',
    componentType: 'mobilestepper',
    lowercase: 'mobilestepper',
    uppercamelcase: 'MobileStepper',
    lowercamelcase: 'mobileStepper',
    snakecase: 'MOBILE_STEPPER',
    kebabcase: 'mobile-stepper',
    disabled: false,
    category: 'navigations',
    capitalizedcategory: 'Navigations',
  },
  {
    component: 'Modal',
    componentType: 'modal',
    lowercase: 'modal',
    uppercamelcase: 'Modal',
    lowercamelcase: 'modal',
    snakecase: 'MODAL',
    kebabcase: 'modal',
    disabled: false,
    category: 'layouts',
    capitalizedcategory: 'Layouts',
  },
  {
    component: 'NativeSelect',
    componentType: 'nativeselect',
    lowercase: 'nativeselect',
    uppercamelcase: 'NativeSelect',
    lowercamelcase: 'nativeSelect',
    snakecase: 'NATIVE_SELECT',
    kebabcase: 'native-select',
    disabled: false,
    category: 'selects',
    capitalizedcategory: 'Selects',
  },
  {
    component: 'Pagination',
    componentType: 'pagination',
    lowercase: 'pagination',
    uppercamelcase: 'Pagination',
    lowercamelcase: 'pagination',
    snakecase: 'PAGINATION',
    kebabcase: 'pagination',
    disabled: false,
    category: 'navigations',
    capitalizedcategory: 'Navigations',
  },
  {
    component: 'Paper',
    componentType: 'paper',
    lowercase: 'paper',
    uppercamelcase: 'Paper',
    lowercamelcase: 'paper',
    snakecase: 'PAPER',
    kebabcase: 'paper',
    disabled: false,
    category: 'layouts',
    capitalizedcategory: 'Layouts',
  },
  {
    component: 'Popover',
    componentType: 'popover',
    lowercase: 'popover',
    uppercamelcase: 'Popover',
    lowercamelcase: 'popover',
    snakecase: 'POPOVER',
    kebabcase: 'popover',
    disabled: false,
    category: 'popups',
    capitalizedcategory: 'Popups',
  },
  {
    component: 'Popper',
    componentType: 'popper',
    lowercase: 'popper',
    uppercamelcase: 'Popper',
    lowercamelcase: 'popper',
    snakecase: 'POPPER',
    kebabcase: 'popper',
    disabled: false,
    category: 'popups',
    capitalizedcategory: 'Popups',
  },
  {
    component: 'Radio',
    componentType: 'radio',
    lowercase: 'radio',
    uppercamelcase: 'Radio',
    lowercamelcase: 'radio',
    snakecase: 'RADIO',
    kebabcase: 'radio',
    disabled: false,
    category: 'inputs',
    capitalizedcategory: 'Inputs',
  },
  {
    component: 'RadioGroup',
    componentType: 'radiogroup',
    lowercase: 'radiogroup',
    uppercamelcase: 'RadioGroup',
    lowercamelcase: 'radioGroup',
    snakecase: 'RADIO_GROUP',
    kebabcase: 'radio-group',
    disabled: false,
    category: 'inputs',
    capitalizedcategory: 'Inputs',
  },
  {
    component: 'Rating',
    componentType: 'rating',
    lowercase: 'rating',
    uppercamelcase: 'Rating',
    lowercamelcase: 'rating',
    snakecase: 'RATING',
    kebabcase: 'rating',
    disabled: false,
    category: 'inputs',
    capitalizedcategory: 'Inputs',
  },
  {
    component: 'Select',
    componentType: 'select',
    lowercase: 'select',
    uppercamelcase: 'Select',
    lowercamelcase: 'select',
    snakecase: 'SELECT',
    kebabcase: 'select',
    disabled: false,
    category: 'selects',
    capitalizedcategory: 'Selects',
  },
  {
    component: 'Skeleton',
    componentType: 'skeleton',
    lowercase: 'skeleton',
    uppercamelcase: 'Skeleton',
    lowercamelcase: 'skeleton',
    snakecase: 'SKELETON',
    kebabcase: 'skeleton',
    disabled: false,
    category: 'layouts',
    capitalizedcategory: 'Layouts',
  },
  {
    component: 'Slide',
    componentType: 'slide',
    lowercase: 'slide',
    uppercamelcase: 'Slide',
    lowercamelcase: 'slide',
    snakecase: 'SLIDE',
    kebabcase: 'slide',
    disabled: false,
    category: 'animations',
    capitalizedcategory: 'Animations',
  },
  {
    component: 'Slider',
    componentType: 'slider',
    lowercase: 'slider',
    uppercamelcase: 'Slider',
    lowercamelcase: 'slider',
    snakecase: 'SLIDER',
    kebabcase: 'slider',
    disabled: false,
    category: 'inputs',
    capitalizedcategory: 'Inputs',
  },
  {
    component: 'Snackbar',
    componentType: 'snackbar',
    lowercase: 'snackbar',
    uppercamelcase: 'Snackbar',
    lowercamelcase: 'snackbar',
    snakecase: 'SNACKBAR',
    kebabcase: 'snackbar',
    disabled: false,
    category: 'popups',
    capitalizedcategory: 'Popups',
  },
  {
    component: 'SpeedDial',
    componentType: 'speeddial',
    lowercase: 'speeddial',
    uppercamelcase: 'SpeedDial',
    lowercamelcase: 'speedDial',
    snakecase: 'SPEED_DIAL',
    kebabcase: 'speed-dial',
    disabled: false,
    category: 'buttons',
    capitalizedcategory: 'Buttons',
  },
  {
    component: 'Stack',
    componentType: 'stack',
    lowercase: 'stack',
    uppercamelcase: 'Stack',
    lowercamelcase: 'stack',
    snakecase: 'STACK',
    kebabcase: 'stack',
    disabled: false,
    category: 'layouts',
    capitalizedcategory: 'Layouts',
  },
  {
    component: 'Stepper',
    componentType: 'stepper',
    lowercase: 'stepper',
    uppercamelcase: 'Stepper',
    lowercamelcase: 'stepper',
    snakecase: 'STEPPER',
    kebabcase: 'stepper',
    disabled: false,
    category: 'navigations',
    capitalizedcategory: 'Navigations',
  },
  {
    component: 'SvgIcon',
    componentType: 'svgicon',
    lowercase: 'svgicon',
    uppercamelcase: 'SvgIcon',
    lowercamelcase: 'svgIcon',
    snakecase: 'SVG_ICON',
    kebabcase: 'svg-icon',
    disabled: false,
    category: 'displays',
    capitalizedcategory: 'Displays',
  },
  {
    component: 'SwipeableDrawer',
    componentType: 'swipeabledrawer',
    lowercase: 'swipeabledrawer',
    uppercamelcase: 'SwipeableDrawer',
    lowercamelcase: 'swipeableDrawer',
    snakecase: 'SWIPEABLE_DRAWER',
    kebabcase: 'swipeable-drawer',
    disabled: false,
    category: 'navigations',
    capitalizedcategory: 'Navigations',
  },
  {
    component: 'Switch',
    componentType: 'switch',
    lowercase: 'switch',
    uppercamelcase: 'Switch',
    lowercamelcase: 'switch',
    snakecase: 'SWITCH',
    kebabcase: 'switch',
    disabled: false,
    category: 'inputs',
    capitalizedcategory: 'Inputs',
  },
  {
    component: 'Table',
    componentType: 'table',
    lowercase: 'table',
    uppercamelcase: 'Table',
    lowercamelcase: 'table',
    snakecase: 'TABLE',
    kebabcase: 'table',
    disabled: false,
    category: 'tables',
    capitalizedcategory: 'Tables',
  },
  {
    component: 'Tabs',
    componentType: 'tabs',
    lowercase: 'tabs',
    uppercamelcase: 'Tabs',
    lowercamelcase: 'tabs',
    snakecase: 'TABS',
    kebabcase: 'tabs',
    disabled: false,
    category: 'navigations',
    capitalizedcategory: 'Navigations',
  },
  {
    component: 'TextField',
    componentType: 'textfield',
    lowercase: 'textfield',
    uppercamelcase: 'TextField',
    lowercamelcase: 'textField',
    snakecase: 'TEXT_FIELD',
    kebabcase: 'text-field',
    disabled: true,
    category: 'inputs',
    capitalizedcategory: 'Inputs',
  },
  {
    component: 'Timeline',
    componentType: 'timeline',
    lowercase: 'timeline',
    uppercamelcase: 'Timeline',
    lowercamelcase: 'timeline',
    snakecase: 'TIMELINE',
    kebabcase: 'timeline',
    disabled: true,
    category: 'displays',
    capitalizedcategory: 'Displays',
  },
  {
    component: 'ToggleButton',
    componentType: 'togglebutton',
    lowercase: 'togglebutton',
    uppercamelcase: 'ToggleButton',
    lowercamelcase: 'toggleButton',
    snakecase: 'TOGGLE_BUTTON',
    kebabcase: 'toggle-button',
    disabled: false,
    category: 'buttons',
    capitalizedcategory: 'Buttons',
  },
  {
    component: 'ToggleButtonGroup',
    componentType: 'togglebuttongroup',
    lowercase: 'togglebuttongroup',
    uppercamelcase: 'ToggleButtonGroup',
    lowercamelcase: 'toggleButtonGroup',
    snakecase: 'TOGGLE_BUTTON_GROUP',
    kebabcase: 'toggle-button-group',
    disabled: false,
    category: 'buttons',
    capitalizedcategory: 'Buttons',
  },
  {
    component: 'Toolbar',
    componentType: 'toolbar',
    lowercase: 'toolbar',
    uppercamelcase: 'Toolbar',
    lowercamelcase: 'toolbar',
    snakecase: 'TOOLBAR',
    kebabcase: 'toolbar',
    disabled: false,
    category: 'navigations',
    capitalizedcategory: 'Navigations',
  },
  {
    component: 'Tooltip',
    componentType: 'tooltip',
    lowercase: 'tooltip',
    uppercamelcase: 'Tooltip',
    lowercamelcase: 'tooltip',
    snakecase: 'TOOLTIP',
    kebabcase: 'tooltip',
    disabled: false,
    category: 'popups',
    capitalizedcategory: 'Popups',
  },
  {
    component: 'Typography',
    componentType: 'typography',
    lowercase: 'typography',
    uppercamelcase: 'Typography',
    lowercamelcase: 'typography',
    snakecase: 'TYPOGRAPHY',
    kebabcase: 'typography',
    disabled: true,
    category: 'texts',
    capitalizedcategory: 'Texts',
  },
  {
    component: 'Zoom',
    componentType: 'zoom',
    lowercase: 'zoom',
    uppercamelcase: 'Zoom',
    lowercamelcase: 'zoom',
    snakecase: 'ZOOM',
    kebabcase: 'zoom',
    disabled: false,
    category: 'animations',
    capitalizedcategory: 'Animations',
  },
];
